name: Add Size Label to PR

on: 
  pull_request:
    types: [opened, edited, reopened]

jobs:
  contribution_inspector:
    runs-on: ubuntu-latest
    name: Add Size Label to PR
    steps:
    - name: All Checks
      uses: flowdify/add-size-label-to-pr@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull-request--size-small: 50
        pull-request--size-medium: 200
        pull-request--size-large: 400